/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classmaster.ui.Admin;

import classmaster.models.Account;
import classmaster.repository.AuthRepository;
import classmaster.repository.Component;
import classmaster.repository.ComponentRegistry;
import classmaster.ui.ChangePassword;
import classmaster.ui.Login;
import classmaster.utils.Page;

/**
 *
 * @author Mishel Fernando
 */
public class HomePage extends javax.swing.JFrame implements Page {
    private AuthRepository authRepository;
    private Account currentUser;
     
    public HomePage() {
        Component Component = ComponentRegistry.getInstance()
                .getComponent("AuthRepository");
        if (Component instanceof AuthRepository) {
            this.authRepository = (AuthRepository) Component;
        }
        
        this.currentUser = this.authRepository.getCurrentAccount();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuStaff = new javax.swing.JMenu();
        jMnuItmAddStaff = new javax.swing.JMenuItem();
        jMnuTeacher = new javax.swing.JMenu();
        jMnuItmAddTeacher = new javax.swing.JMenuItem();
        jMnuClass = new javax.swing.JMenu();
        jMnuItmCreateNewClass = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ClassMaster");
        setResizable(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classmaster/images/logo/adminHome.png"))); // NOI18N

        jMnuStaff.setText("Staff");

        jMnuItmAddStaff.setText("Add Staff");
        jMnuItmAddStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuItmAddStaffActionPerformed(evt);
            }
        });
        jMnuStaff.add(jMnuItmAddStaff);

        jMenuBar1.add(jMnuStaff);

        jMnuTeacher.setText("Teacher");

        jMnuItmAddTeacher.setText("Add Teacher");
        jMnuItmAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuItmAddTeacherActionPerformed(evt);
            }
        });
        jMnuTeacher.add(jMnuItmAddTeacher);

        jMenuBar1.add(jMnuTeacher);

        jMnuClass.setText("Classes");

        jMnuItmCreateNewClass.setText("Create new class");
        jMnuItmCreateNewClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuItmCreateNewClassActionPerformed(evt);
            }
        });
        jMnuClass.add(jMnuItmCreateNewClass);

        jMenuBar1.add(jMnuClass);

        jMenu4.setText("Edit");

        jMenuItem4.setText("Change Password");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

        jMenu3.setText("Exit");

        jMenuItem1.setText("Log out");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuItmAddStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuItmAddStaffActionPerformed
        new AddStaffForm(this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMnuItmAddStaffActionPerformed

    private void jMnuItmAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuItmAddTeacherActionPerformed
        new AddTeacherForm(this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMnuItmAddTeacherActionPerformed

    private void jMnuItmCreateNewClassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuItmCreateNewClassActionPerformed
        new CreateClass(this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMnuItmCreateNewClassActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        new ChangePassword(this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(this.authRepository.getCurrentAccount() != null){
            this.currentUser = null;
            setVisible(false);
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu jMnuClass;
    private javax.swing.JMenuItem jMnuItmAddStaff;
    private javax.swing.JMenuItem jMnuItmAddTeacher;
    private javax.swing.JMenuItem jMnuItmCreateNewClass;
    private javax.swing.JMenu jMnuStaff;
    private javax.swing.JMenu jMnuTeacher;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onChildPageClose() {
        this.setVisible(true);
    }


}
